version: '3'

services:

  node:
    container_name: node
    restart: always
    build:
      context: ./node
    depends_on:
      - db
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    ports: 
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - node
    networks: 
      - node-network
    ports: 
      - "8080:80"

  db:
    build: 
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/volume:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

    

networks: 
  node-network:
    driver: bridge    